name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Match dev environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint with black and isort
        run: |
          black --check sqlviz tests
          isort --check sqlviz tests

      - name: Type check with mypy (strict mode)
        run: |
          mypy sqlviz --strict --pretty

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Smoke test CLI
        run: |
          python -m sqlviz.cli --help
