name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or '3.x' for any Python 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Lint with black and isort
        run: |
          black --check sqlviz tests
          isort --check sqlviz tests

      - name: Type check with mypy
        run: |
          mypy sqlviz

      - name: Run tests with pytest
        run: |
          pytest

      - name: Smoke test CLI
        run: |
          sqlviz --help
